### PR TITLE
Submissions: Use a plain table for listing pending submissions

### LINKED ISSUE #16: Submission page: Remove thumbnail of pending photos
> […] the photos are on a CDN and filenames for all sizes of the submitted photo can be determined based on the thumbnail filename. By revealing the photo path, we would expose ourselves to a brief window before moderation where the potentially guideline-violating photo is publicly available and known.

_Originally posted by @coffee2code in https://github.com/WordPress/wporg-photo-directory/discussions/1#discussioncomment-11328150_

> Regarding the info displayed in the table, we could continue without showing the thumbnail and just update the style of the current table (the one shown in this screenshot) with the latest changes.

_Originally posted by @fcoveram in https://github.com/WordPress/wporg-photo-directory/discussions/1#discussioncomment-11334241_

Variations were [shared in the discussion](https://github.com/WordPress/wporg-photo-directory/discussions/1#discussioncomment-11342060), and it was decided to go with a plain table version.

### PR DESCRIPTION
**Pull request by ryelle**
Fixes WordPress/wporg-main-2022#16 — This swaps the "pending list" with photo thumbnail with a plain table, no photo.

**Screenshots**

submission-page

On small screens, the default table behavior is to scroll. Does this work, or should I try to add some CSS to switch to a single-column display?

submissions-small

### CODE REVIEW

**Comment by fcoveram** [comment]
A single column sounds good to me.

I also notice that header in Inter is slightly bigger than its parent in Garamond. Is that because there is no font size defined for small breakpoints?

**Comment by ryelle** [comment]
> I also notice that header in Inter is slightly bigger than its parent in Garamond. Is that because there is no font size defined for small breakpoints?

Yeah, it looks like that's the case. Though technically the `h1` is bigger at 26px, than the `h2` at `24px`, but visually it does look smaller. Is there supposed to be a smaller font size here? Where is the font reference for the Inter style headings? All I see in the WordPress.org Design Library figma are the Garamond-style ones.

Screenshot 2024-11-25 at 11 36 13 AM

**Comment by ryelle** [comment]
@fcoveram For a single column, how's this?



Or maybe without the inner borders?

**Comment by fcoveram** [comment]
For the table style, I like the version without inner borders. And we could also remove the space between boxes to make it look like a single element (table).

Regarding text styles, I just created the ticket [wporg-main-2022#522](https://github.com/WordPress/wporg-parent-2021/issues/163) requesting an update.

**Comment by ryelle** [comment]
Okay, the table looks like this now:

**Comment by fcoveram** [comment]
That looks good to me. Thanks

**Pull request merged**
